spring.application.name=cooperativaBackend


# =========================================================
# ORACLE DATABASE
# =========================================================

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}

spring.datasource.username=${DB_USERNAME:COOPERATIVA_APP}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


# =========================================================
# SERVIDOR
# =========================================================

server.port=${PORT:8080}


# =========================================================
# CARGA DE DOCUMENTOS
# =========================================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET}

jwt.expiration=3600000


# =========================================================
# CORREO - GMAIL SMTP
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true